root - INFO - Grid Search Tuner Matrix Multiplication - 2023-07-10 20:30:16.010635
autotvm - DEBUG - waiting for device...
autotvm - DEBUG - device available
autotvm - INFO - Get devices for measurement successfully!
autotvm - DEBUG - No: 1	GFLOPS: 0.54/0.54	result: MeasureResult(costs=(32.060816275,), error_no=MeasureErrorNo.NO_ERROR, all_cost=65.68254446983337, timestamp=1689039087.774269)	[('tile_y', 2), ('tile_x', 2)],None,0
autotvm - DEBUG - No: 2	GFLOPS: 0.63/0.63	result: MeasureResult(costs=(27.399995483999998,), error_no=MeasureErrorNo.NO_ERROR, all_cost=56.83339715003967, timestamp=1689039143.1107535)	[('tile_y', 4), ('tile_x', 2)],None,1
autotvm - DEBUG - No: 3	GFLOPS: 0.61/0.63	result: MeasureResult(costs=(28.196561266,), error_no=MeasureErrorNo.NO_ERROR, all_cost=58.34678626060486, timestamp=1689039199.88675)	[('tile_y', 8), ('tile_x', 2)],None,2
autotvm - DEBUG - No: 4	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 16), ('tile_x', 2)],None,3
autotvm - DEBUG - No: 5	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 32), ('tile_x', 2)],None,4
autotvm - DEBUG - No: 6	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 64), ('tile_x', 2)],None,5
autotvm - DEBUG - No: 7	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 128), ('tile_x', 2)],None,6
autotvm - DEBUG - No: 8	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 256), ('tile_x', 2)],None,7
autotvm - DEBUG - No: 9	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 512), ('tile_x', 2)],None,8
autotvm - DEBUG - No: 10	GFLOPS: 0.00/0.63	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_y', 1024), ('tile_x', 2)],None,9
autotvm - DEBUG - No: 11	GFLOPS: 0.59/0.63	result: MeasureResult(costs=(29.137351255000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=59.98096323013306, timestamp=1689040660.7504287)	[('tile_y', 2), ('tile_x', 4)],None,10
autotvm - DEBUG - No: 12	GFLOPS: 0.77/0.77	result: MeasureResult(costs=(22.362021375,), error_no=MeasureErrorNo.NO_ERROR, all_cost=46.6075165271759, timestamp=1689040705.6875002)	[('tile_y', 4), ('tile_x', 4)],None,11
autotvm - DEBUG - No: 13	GFLOPS: 0.86/0.86	result: MeasureResult(costs=(19.936410707,), error_no=MeasureErrorNo.NO_ERROR, all_cost=41.48808002471924, timestamp=1689040746.158345)	[('tile_y', 8), ('tile_x', 4)],None,12
autotvm - DEBUG - No: 14	GFLOPS: 0.65/0.86	result: MeasureResult(costs=(26.455918723,), error_no=MeasureErrorNo.NO_ERROR, all_cost=54.85863447189331, timestamp=1689040799.4489186)	[('tile_y', 16), ('tile_x', 4)],None,13
autotvm - DEBUG - No: 15	GFLOPS: 0.74/0.86	result: MeasureResult(costs=(23.124117091,), error_no=MeasureErrorNo.NO_ERROR, all_cost=47.892643213272095, timestamp=1689040845.8983312)	[('tile_y', 32), ('tile_x', 4)],None,14
autotvm - DEBUG - No: 16	GFLOPS: 0.93/0.93	result: MeasureResult(costs=(18.477619781,), error_no=MeasureErrorNo.NO_ERROR, all_cost=38.952998638153076, timestamp=1689040883.4381192)	[('tile_y', 64), ('tile_x', 4)],None,15
autotvm - DEBUG - No: 17	GFLOPS: 0.99/0.99	result: MeasureResult(costs=(17.408797217,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.602216482162476, timestamp=1689040918.8007712)	[('tile_y', 128), ('tile_x', 4)],None,16
autotvm - DEBUG - No: 18	GFLOPS: 0.95/0.99	result: MeasureResult(costs=(18.111755061,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.03996276855469, timestamp=1689040953.8870282)	[('tile_y', 256), ('tile_x', 4)],None,17
autotvm - DEBUG - No: 19	GFLOPS: 1.12/1.12	result: MeasureResult(costs=(15.365106014999999,), error_no=MeasureErrorNo.NO_ERROR, all_cost=32.701870918273926, timestamp=1689040985.2179801)	[('tile_y', 512), ('tile_x', 4)],None,18
autotvm - DEBUG - No: 20	GFLOPS: 0.68/1.12	result: MeasureResult(costs=(25.22259733,), error_no=MeasureErrorNo.NO_ERROR, all_cost=51.4187376499176, timestamp=1689041036.083904)	[('tile_y', 1024), ('tile_x', 4)],None,19
autotvm - DEBUG - No: 21	GFLOPS: 0.72/1.12	result: MeasureResult(costs=(23.743242446,), error_no=MeasureErrorNo.NO_ERROR, all_cost=48.74520707130432, timestamp=1689041083.848376)	[('tile_y', 2), ('tile_x', 8)],None,20
autotvm - DEBUG - No: 22	GFLOPS: 0.94/1.12	result: MeasureResult(costs=(18.267235573999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=38.03158235549927, timestamp=1689041120.638783)	[('tile_y', 4), ('tile_x', 8)],None,21
autotvm - DEBUG - No: 23	GFLOPS: 1.01/1.12	result: MeasureResult(costs=(17.086755709000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=34.39470171928406, timestamp=1689041155.022641)	[('tile_y', 8), ('tile_x', 8)],None,22
autotvm - DEBUG - No: 24	GFLOPS: 1.74/1.74	result: MeasureResult(costs=(9.878005107000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=20.98081874847412, timestamp=1689041175.1534548)	[('tile_y', 16), ('tile_x', 8)],None,23
autotvm - DEBUG - No: 25	GFLOPS: 2.17/2.17	result: MeasureResult(costs=(7.922766588,), error_no=MeasureErrorNo.NO_ERROR, all_cost=17.937169790267944, timestamp=1689041191.6368384)	[('tile_y', 32), ('tile_x', 8)],None,24
autotvm - DEBUG - No: 26	GFLOPS: 2.49/2.49	result: MeasureResult(costs=(6.8952864730000005,), error_no=MeasureErrorNo.NO_ERROR, all_cost=15.852465152740479, timestamp=1689041205.8040562)	[('tile_y', 64), ('tile_x', 8)],None,25
autotvm - DEBUG - No: 27	GFLOPS: 3.04/3.04	result: MeasureResult(costs=(5.646274866,), error_no=MeasureErrorNo.NO_ERROR, all_cost=13.300719499588013, timestamp=1689041218.1260262)	[('tile_y', 128), ('tile_x', 8)],None,26
autotvm - DEBUG - No: 28	GFLOPS: 2.94/3.04	result: MeasureResult(costs=(5.848066811,), error_no=MeasureErrorNo.NO_ERROR, all_cost=12.686203241348267, timestamp=1689041230.2482626)	[('tile_y', 256), ('tile_x', 8)],None,27
autotvm - DEBUG - No: 29	GFLOPS: 2.58/3.04	result: MeasureResult(costs=(6.668226764,), error_no=MeasureErrorNo.NO_ERROR, all_cost=14.905317306518555, timestamp=1689041243.9485674)	[('tile_y', 512), ('tile_x', 8)],None,28
autotvm - DEBUG - No: 30	GFLOPS: 0.96/3.04	result: MeasureResult(costs=(17.83889676,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.30894732475281, timestamp=1689041280.1097708)	[('tile_y', 1024), ('tile_x', 8)],None,29
autotvm - DEBUG - No: 31	GFLOPS: 0.90/3.04	result: MeasureResult(costs=(19.047203362,), error_no=MeasureErrorNo.NO_ERROR, all_cost=39.94754076004028, timestamp=1689041319.4051352)	[('tile_y', 2), ('tile_x', 16)],None,30
autotvm - DEBUG - No: 32	GFLOPS: 1.53/3.04	result: MeasureResult(costs=(11.196255619,), error_no=MeasureErrorNo.NO_ERROR, all_cost=23.269325017929077, timestamp=1689041342.1804283)	[('tile_y', 4), ('tile_x', 16)],None,31
autotvm - DEBUG - No: 33	GFLOPS: 1.78/3.04	result: MeasureResult(costs=(9.626926321000001,), error_no=MeasureErrorNo.NO_ERROR, all_cost=20.280360460281372, timestamp=1689041361.97045)	[('tile_y', 8), ('tile_x', 16)],None,32
autotvm - DEBUG - No: 34	GFLOPS: 2.45/3.04	result: MeasureResult(costs=(7.0135761,), error_no=MeasureErrorNo.NO_ERROR, all_cost=15.094697713851929, timestamp=1689041376.4749353)	[('tile_y', 16), ('tile_x', 16)],None,33
autotvm - DEBUG - No: 35	GFLOPS: 2.93/3.04	result: MeasureResult(costs=(5.867386768,), error_no=MeasureErrorNo.NO_ERROR, all_cost=11.989760637283325, timestamp=1689041388.42018)	[('tile_y', 32), ('tile_x', 16)],None,34
autotvm - DEBUG - No: 36	GFLOPS: 3.25/3.25	result: MeasureResult(costs=(5.291193278,), error_no=MeasureErrorNo.NO_ERROR, all_cost=12.256102800369263, timestamp=1689041399.3797884)	[('tile_y', 64), ('tile_x', 16)],None,35
autotvm - DEBUG - No: 37	GFLOPS: 3.42/3.42	result: MeasureResult(costs=(5.016785885,), error_no=MeasureErrorNo.NO_ERROR, all_cost=10.845476388931274, timestamp=1689041409.8301582)	[('tile_y', 128), ('tile_x', 16)],None,36
autotvm - DEBUG - No: 38	GFLOPS: 3.36/3.42	result: MeasureResult(costs=(5.109901239,), error_no=MeasureErrorNo.NO_ERROR, all_cost=10.52441954612732, timestamp=1689041420.266102)	[('tile_y', 256), ('tile_x', 16)],None,37
autotvm - DEBUG - No: 39	GFLOPS: 3.23/3.42	result: MeasureResult(costs=(5.32584495,), error_no=MeasureErrorNo.NO_ERROR, all_cost=11.418747663497925, timestamp=1689041431.2874923)	[('tile_y', 512), ('tile_x', 16)],None,38
autotvm - DEBUG - No: 40	GFLOPS: 1.32/3.42	result: MeasureResult(costs=(12.980927832999999,), error_no=MeasureErrorNo.NO_ERROR, all_cost=27.645342588424683, timestamp=1689041457.510523)	[('tile_y', 1024), ('tile_x', 16)],None,39
autotvm - DEBUG - No: 41	GFLOPS: 1.64/3.42	result: MeasureResult(costs=(10.451277829,), error_no=MeasureErrorNo.NO_ERROR, all_cost=22.72346067428589, timestamp=1689041478.7807956)	[('tile_y', 2), ('tile_x', 32)],None,40
autotvm - DEBUG - No: 42	GFLOPS: 1.68/3.42	result: MeasureResult(costs=(10.244440827,), error_no=MeasureErrorNo.NO_ERROR, all_cost=22.48519468307495, timestamp=1689041499.7911756)	[('tile_y', 4), ('tile_x', 32)],None,41
autotvm - DEBUG - No: 43	GFLOPS: 2.68/3.42	result: MeasureResult(costs=(6.4121785330000005,), error_no=MeasureErrorNo.NO_ERROR, all_cost=13.744297742843628, timestamp=1689041513.0340054)	[('tile_y', 8), ('tile_x', 32)],None,42
autotvm - DEBUG - No: 44	GFLOPS: 3.19/3.42	result: MeasureResult(costs=(5.385423399,), error_no=MeasureErrorNo.NO_ERROR, all_cost=12.712352752685547, timestamp=1689041524.007621)	[('tile_y', 16), ('tile_x', 32)],None,43
autotvm - DEBUG - No: 45	GFLOPS: 5.48/5.48	result: MeasureResult(costs=(3.1359425419999996,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.029415130615234, timestamp=1689041530.6609633)	[('tile_y', 32), ('tile_x', 32)],None,44
autotvm - DEBUG - No: 46	GFLOPS: 5.65/5.65	result: MeasureResult(costs=(3.0404410189999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.913599491119385, timestamp=1689041537.1611845)	[('tile_y', 64), ('tile_x', 32)],None,45
autotvm - DEBUG - No: 47	GFLOPS: 5.72/5.72	result: MeasureResult(costs=(3.001869212,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.089613437652588, timestamp=1689041543.5391755)	[('tile_y', 128), ('tile_x', 32)],None,46
autotvm - DEBUG - No: 48	GFLOPS: 5.70/5.72	result: MeasureResult(costs=(3.015580294,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.53289532661438, timestamp=1689041549.9469376)	[('tile_y', 256), ('tile_x', 32)],None,47
autotvm - DEBUG - No: 49	GFLOPS: 4.84/5.72	result: MeasureResult(costs=(3.550816056,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.437414169311523, timestamp=1689041557.2840412)	[('tile_y', 512), ('tile_x', 32)],None,48
autotvm - DEBUG - No: 50	GFLOPS: 1.82/5.72	result: MeasureResult(costs=(9.414533363,), error_no=MeasureErrorNo.NO_ERROR, all_cost=19.99557614326477, timestamp=1689041576.484097)	[('tile_y', 1024), ('tile_x', 32)],None,49
autotvm - DEBUG - No: 51	GFLOPS: 1.65/5.72	result: MeasureResult(costs=(10.418023092,), error_no=MeasureErrorNo.NO_ERROR, all_cost=21.829288482666016, timestamp=1689041597.5352116)	[('tile_y', 2), ('tile_x', 64)],None,50
autotvm - DEBUG - No: 52	GFLOPS: 2.66/5.72	result: MeasureResult(costs=(6.455782065,), error_no=MeasureErrorNo.NO_ERROR, all_cost=14.943741798400879, timestamp=1689041610.864938)	[('tile_y', 4), ('tile_x', 64)],None,51
autotvm - DEBUG - No: 53	GFLOPS: 3.24/5.72	result: MeasureResult(costs=(5.307471079,), error_no=MeasureErrorNo.NO_ERROR, all_cost=11.634280681610107, timestamp=1689041621.874482)	[('tile_y', 8), ('tile_x', 64)],None,52
autotvm - DEBUG - No: 54	GFLOPS: 3.90/5.72	result: MeasureResult(costs=(4.399524028,), error_no=MeasureErrorNo.NO_ERROR, all_cost=10.326620817184448, timestamp=1689041631.2219374)	[('tile_y', 16), ('tile_x', 64)],None,53
autotvm - DEBUG - No: 55	GFLOPS: 6.57/6.57	result: MeasureResult(costs=(2.613354185,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.694002866744995, timestamp=1689041636.8704405)	[('tile_y', 32), ('tile_x', 64)],None,54
autotvm - DEBUG - No: 56	GFLOPS: 6.07/6.57	result: MeasureResult(costs=(2.828724991,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.5522613525390625, timestamp=1689041642.909582)	[('tile_y', 64), ('tile_x', 64)],None,55
autotvm - DEBUG - No: 57	GFLOPS: 6.08/6.57	result: MeasureResult(costs=(2.826382055,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.974845886230469, timestamp=1689041648.942236)	[('tile_y', 128), ('tile_x', 64)],None,56
autotvm - DEBUG - No: 58	GFLOPS: 6.13/6.57	result: MeasureResult(costs=(2.8045879530000004,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.045719623565674, timestamp=1689041654.975656)	[('tile_y', 256), ('tile_x', 64)],None,57
autotvm - DEBUG - No: 59	GFLOPS: 5.19/6.57	result: MeasureResult(costs=(3.307766908,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.153302192687988, timestamp=1689041661.7961204)	[('tile_y', 512), ('tile_x', 64)],None,58
autotvm - DEBUG - No: 60	GFLOPS: 2.25/6.57	result: MeasureResult(costs=(7.646369770000001,), error_no=MeasureErrorNo.NO_ERROR, all_cost=16.12800407409668, timestamp=1689041677.4600894)	[('tile_y', 1024), ('tile_x', 64)],None,59
autotvm - DEBUG - No: 61	GFLOPS: 2.50/6.57	result: MeasureResult(costs=(6.8630253,), error_no=MeasureErrorNo.NO_ERROR, all_cost=15.288687944412231, timestamp=1689041691.6084058)	[('tile_y', 2), ('tile_x', 128)],None,60
autotvm - DEBUG - No: 62	GFLOPS: 3.92/6.57	result: MeasureResult(costs=(4.382196632,), error_no=MeasureErrorNo.NO_ERROR, all_cost=9.638918161392212, timestamp=1689041700.7868183)	[('tile_y', 4), ('tile_x', 128)],None,61
autotvm - DEBUG - No: 63	GFLOPS: 5.50/6.57	result: MeasureResult(costs=(3.120891516,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.851342678070068, timestamp=1689041707.4152088)	[('tile_y', 8), ('tile_x', 128)],None,62
autotvm - DEBUG - No: 64	GFLOPS: 6.59/6.59	result: MeasureResult(costs=(2.605538982,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.787740707397461, timestamp=1689041713.046134)	[('tile_y', 16), ('tile_x', 128)],None,63
autotvm - DEBUG - No: 65	GFLOPS: 6.78/6.78	result: MeasureResult(costs=(2.534472217,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.473257780075073, timestamp=1689041718.4948382)	[('tile_y', 32), ('tile_x', 128)],None,64
autotvm - DEBUG - No: 66	GFLOPS: 6.21/6.78	result: MeasureResult(costs=(2.76650304,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.681522846221924, timestamp=1689041724.4029431)	[('tile_y', 64), ('tile_x', 128)],None,65
autotvm - DEBUG - No: 67	GFLOPS: 5.67/6.78	result: MeasureResult(costs=(3.028707319,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.852026462554932, timestamp=1689041730.8837082)	[('tile_y', 128), ('tile_x', 128)],None,66
autotvm - DEBUG - No: 68	GFLOPS: 5.62/6.78	result: MeasureResult(costs=(3.056427248,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.283303260803223, timestamp=1689041737.5499706)	[('tile_y', 256), ('tile_x', 128)],None,67
autotvm - DEBUG - No: 69	GFLOPS: 5.53/6.78	result: MeasureResult(costs=(3.1090119439999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.779785871505737, timestamp=1689041744.1485426)	[('tile_y', 512), ('tile_x', 128)],None,68
autotvm - DEBUG - No: 70	GFLOPS: 2.29/6.78	result: MeasureResult(costs=(7.506081172,), error_no=MeasureErrorNo.NO_ERROR, all_cost=16.06346368789673, timestamp=1689041759.586186)	[('tile_y', 1024), ('tile_x', 128)],None,69
autotvm - DEBUG - No: 71	GFLOPS: 2.37/6.78	result: MeasureResult(costs=(7.235673065,), error_no=MeasureErrorNo.NO_ERROR, all_cost=14.594642400741577, timestamp=1689041773.196166)	[('tile_y', 2), ('tile_x', 256)],None,70
autotvm - DEBUG - No: 72	GFLOPS: 4.61/6.78	result: MeasureResult(costs=(3.728148661,), error_no=MeasureErrorNo.NO_ERROR, all_cost=8.290763854980469, timestamp=1689041781.043957)	[('tile_y', 4), ('tile_x', 256)],None,71
autotvm - DEBUG - No: 73	GFLOPS: 5.98/6.78	result: MeasureResult(costs=(2.873138065,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.127613306045532, timestamp=1689041787.2167678)	[('tile_y', 8), ('tile_x', 256)],None,72
autotvm - DEBUG - No: 74	GFLOPS: 6.84/6.84	result: MeasureResult(costs=(2.5129183779999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.649173021316528, timestamp=1689041792.6255782)	[('tile_y', 16), ('tile_x', 256)],None,73
autotvm - DEBUG - No: 75	GFLOPS: 7.25/7.25	result: MeasureResult(costs=(2.3690253809999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.498345375061035, timestamp=1689041797.745272)	[('tile_y', 32), ('tile_x', 256)],None,74
autotvm - DEBUG - No: 76	GFLOPS: 6.68/7.25	result: MeasureResult(costs=(2.571277187,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.045166492462158, timestamp=1689041803.310378)	[('tile_y', 64), ('tile_x', 256)],None,75
autotvm - DEBUG - No: 77	GFLOPS: 6.41/7.25	result: MeasureResult(costs=(2.6817114660000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.241461992263794, timestamp=1689041809.2108598)	[('tile_y', 128), ('tile_x', 256)],None,76
autotvm - DEBUG - No: 78	GFLOPS: 6.22/7.25	result: MeasureResult(costs=(2.762436589,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.144053936004639, timestamp=1689041815.1029198)	[('tile_y', 256), ('tile_x', 256)],None,77
autotvm - DEBUG - No: 79	GFLOPS: 6.09/7.25	result: MeasureResult(costs=(2.8197378939999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.082920551300049, timestamp=1689041821.1646917)	[('tile_y', 512), ('tile_x', 256)],None,78
autotvm - DEBUG - No: 80	GFLOPS: 2.98/7.25	result: MeasureResult(costs=(5.763926126,), error_no=MeasureErrorNo.NO_ERROR, all_cost=12.749619007110596, timestamp=1689041833.0646284)	[('tile_y', 1024), ('tile_x', 256)],None,79
autotvm - DEBUG - No: 81	GFLOPS: 3.78/7.25	result: MeasureResult(costs=(4.546043152999999,), error_no=MeasureErrorNo.NO_ERROR, all_cost=9.657045364379883, timestamp=1689041842.3760097)	[('tile_y', 2), ('tile_x', 512)],None,80
autotvm - DEBUG - No: 82	GFLOPS: 5.34/7.25	result: MeasureResult(costs=(3.2195165489999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=7.185367822647095, timestamp=1689041849.2345054)	[('tile_y', 4), ('tile_x', 512)],None,81
autotvm - DEBUG - No: 83	GFLOPS: 6.55/7.25	result: MeasureResult(costs=(2.623914479,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.093212604522705, timestamp=1689041854.8224478)	[('tile_y', 8), ('tile_x', 512)],None,82
autotvm - DEBUG - No: 84	GFLOPS: 7.27/7.27	result: MeasureResult(costs=(2.363012839,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.180936336517334, timestamp=1689041859.926486)	[('tile_y', 16), ('tile_x', 512)],None,83
autotvm - DEBUG - No: 85	GFLOPS: 7.40/7.40	result: MeasureResult(costs=(2.3200379819999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.085050106048584, timestamp=1689041864.9853203)	[('tile_y', 32), ('tile_x', 512)],None,84
autotvm - DEBUG - No: 86	GFLOPS: 7.05/7.40	result: MeasureResult(costs=(2.4373484260000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.954537630081177, timestamp=1689041870.236035)	[('tile_y', 64), ('tile_x', 512)],None,85
autotvm - DEBUG - No: 87	GFLOPS: 6.57/7.40	result: MeasureResult(costs=(2.614310187,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.647692441940308, timestamp=1689041875.7915814)	[('tile_y', 128), ('tile_x', 512)],None,86
autotvm - DEBUG - No: 88	GFLOPS: 6.78/7.40	result: MeasureResult(costs=(2.5325908100000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.529256343841553, timestamp=1689041881.2799606)	[('tile_y', 256), ('tile_x', 512)],None,87
autotvm - DEBUG - No: 89	GFLOPS: 6.30/7.40	result: MeasureResult(costs=(2.724999559,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.237852334976196, timestamp=1689041887.105383)	[('tile_y', 512), ('tile_x', 512)],None,88
autotvm - DEBUG - No: 90	GFLOPS: 3.62/7.40	result: MeasureResult(costs=(4.744135277000001,), error_no=MeasureErrorNo.NO_ERROR, all_cost=9.984949588775635, timestamp=1689041896.9684594)	[('tile_y', 1024), ('tile_x', 512)],None,89
autotvm - DEBUG - No: 91	GFLOPS: 4.70/7.40	result: MeasureResult(costs=(3.658611797,), error_no=MeasureErrorNo.NO_ERROR, all_cost=8.137012958526611, timestamp=1689041904.7040179)	[('tile_y', 2), ('tile_x', 1024)],None,90
autotvm - DEBUG - No: 92	GFLOPS: 6.07/7.40	result: MeasureResult(costs=(2.831285528,), error_no=MeasureErrorNo.NO_ERROR, all_cost=6.18560791015625, timestamp=1689041910.7449014)	[('tile_y', 4), ('tile_x', 1024)],None,91
autotvm - DEBUG - No: 93	GFLOPS: 7.01/7.40	result: MeasureResult(costs=(2.451820343,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.522337198257446, timestamp=1689041916.216184)	[('tile_y', 8), ('tile_x', 1024)],None,92
autotvm - DEBUG - No: 94	GFLOPS: 7.72/7.72	result: MeasureResult(costs=(2.224738194,), error_no=MeasureErrorNo.NO_ERROR, all_cost=4.989284515380859, timestamp=1689041921.0919862)	[('tile_y', 16), ('tile_x', 1024)],None,93
autotvm - DEBUG - No: 95	GFLOPS: 7.80/7.80	result: MeasureResult(costs=(2.201648248,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.171891212463379, timestamp=1689041925.8770185)	[('tile_y', 32), ('tile_x', 1024)],None,94
autotvm - DEBUG - No: 96	GFLOPS: 7.57/7.80	result: MeasureResult(costs=(2.268177197,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.013770580291748, timestamp=1689041930.7901864)	[('tile_y', 64), ('tile_x', 1024)],None,95
autotvm - DEBUG - No: 97	GFLOPS: 7.46/7.80	result: MeasureResult(costs=(2.3021816640000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.435383558273315, timestamp=1689041935.8187053)	[('tile_y', 128), ('tile_x', 1024)],None,96
autotvm - DEBUG - No: 98	GFLOPS: 7.52/7.80	result: MeasureResult(costs=(2.283465919,), error_no=MeasureErrorNo.NO_ERROR, all_cost=4.953567981719971, timestamp=1689041940.7638686)	[('tile_y', 256), ('tile_x', 1024)],None,97
autotvm - DEBUG - No: 99	GFLOPS: 7.14/7.80	result: MeasureResult(costs=(2.404771706,), error_no=MeasureErrorNo.NO_ERROR, all_cost=5.310970783233643, timestamp=1689041945.9491177)	[('tile_y', 512), ('tile_x', 1024)],None,98
autotvm - DEBUG - No: 100	GFLOPS: 4.22/7.80	result: MeasureResult(costs=(4.066438209999999,), error_no=MeasureErrorNo.NO_ERROR, all_cost=8.765778541564941, timestamp=1689041954.6617508)	[('tile_y', 1024), ('tile_x', 1024)],None,99
root - INFO - Elpased time = 2938.4600150585175
autotvm - DEBUG - Finish loading 100 records
